Traceback (most recent call last):
  File "/Users/mazhongjun/miniconda3/envs/jbenv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/mazhongjun/miniconda3/envs/jbenv/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mazhongjun/miniconda3/envs/jbenv/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/mazhongjun/miniconda3/envs/jbenv/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/mazhongjun/miniconda3/envs/jbenv/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/mazhongjun/miniconda3/envs/jbenv/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/mazhongjun/miniconda3/envs/jbenv/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/mazhongjun/miniconda3/envs/jbenv/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plot_points_heading(ais_df)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-9-d1662834521a>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mplot_points_heading[0m[0;34m([0m[0mais_df[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-8-1931aa8fccf4>[0m in [0;36mplot_points_heading[0;34m(df)[0m
[1;32m     17[0m     fig.update_layout(
[1;32m     18[0m         mapbox={
[0;32m---> 19[0;31m             [0;34m'accesstoken'[0m[0;34m:[0m [0mtoken[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     20[0m             [0;34m'style'[0m[0;34m:[0m [0;34m"satellite-streets"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     21[0m             [0;34m'zoom'[0m[0;34m:[0m [0;36m10[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'token' is not defined
NameError: name 'token' is not defined

